
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-zurisaddairj
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-zurisaddairj
  template:
    metadata:
      labels:
        app: front-zurisadairj
    spec:
      containers:
      - image: okteto.dev/zurisaddairj:latest
        name: front-zurisaddairj
        envFrom:
        - configMapRef:
            name: front-zurisaddairj-config
        livenessProbe:
          httpGet:
            path: /ht/
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---

apiVersion: v1
kind: Service
metadata:
  name: front-zurisaddairj
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "front-zurisaddairj"
    port: 8080
  selector:
    app: front-zurisaddairj
